[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Scheduled functions
[[functions]]
  name = "amm-poller"
  schedule = "*/1 * * * *" # every minute

[[functions]]
  name = "fee-worker"
  schedule = "*/5 * * * *" # every 5 minutes
