[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[functions]]
  name = "amm-poller"
  schedule = "*/1 * * * *"

[[functions]]
  name = "fee-worker"
  schedule = "*/5 * * * *"
