[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[functions]]
  name = "amm-poller"
  schedule = "*/1 * * * *"

[[functions]]
  name = "fee-worker"
  schedule = "*/5 * * * *"
